
POST  http://localhost:8000/login
Content-Type: application/json

{
    "email":"diorypribadi2@gmail.com",
    "password":"12345"
}
###
GET http://localhost:8000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySUQiOjEsInVzZXJuYW1lIjoic2luYWdhX3ByaWJhZGkiLCJlbWFpbCI6ImRpb3J5cHJpYmFkaTJAZ21haWwuY29tIiwiaWF0IjoxNjYyMzg0NjA5LCJleHAiOjE2NjI0NzEwMDl9.bzaIodHmJ_SaD2rCbnpUI1hix9ynRyAuRCQUexZBNxM

###
POST  http://localhost:8000/register
Content-Type: application/json

{
    "username":"sinaga_pribadi",
    "email":"diorypribadi2@gmail.com",
    "password":"12345"
}
